# Generated by Django 5.1.6 on 2025-09-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ashaworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('setlimit', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('securitypin', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('subdepartment', models.CharField(max_length=100)),
                ('followup', models.IntegerField(default=0)),
                ('followupdate', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=1000)),
                ('confirm_entry', models.IntegerField(default=0)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='subdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('setlimit', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
