# Generated by Django 5.1.6 on 2025-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='token_no',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
