# Generated by Django 5.1.6 on 2025-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_patients_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='token_no',
            field=models.IntegerField(default=0),
        ),
    ]
