# Generated by Django 5.1.6 on 2025-10-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_alter_patients_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
