# Generated by Django 5.1.6 on 2025-10-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_department_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
