# Generated by Django 5.1.6 on 2025-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_patients_age_patients_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='asha_limit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
