# Generated by Django 5.1.6 on 2025-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_officialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
