# Generated by Django 5.1.6 on 2025-10-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_patients_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
