# Generated by Django 5.1.6 on 2025-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0011_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='confirmed_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
