# Generated by Django 5.1.6 on 2025-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0012_patients_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='agebelow1',
            field=models.IntegerField(default=0),
        ),
    ]
