# Generated by Django 5.1 on 2025-10-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0013_patients_agebelow1'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='rotary_limit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
