# Generated by Django 5.1 on 2025-10-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0014_department_rotary_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='consulted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='consulted_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='medicineamount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='medicineissued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='medicineissued_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
