# Generated by Django 5.1 on 2025-10-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0015_patients_consulted_patients_consulted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
    ]
